version: '3.4'

services:

  mausritter-sheet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8765:8765"
    container_name: mausritter-sheet
    restart: "no"
    working_dir: /app
    command: ["http-server", "./dist", "--port", "8765"]
